// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_Avaliativo_Módulo_02.Data;

namespace Projeto_Avaliativo_Módulo_02.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_Avaliativo_Módulo_02.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf_Cnpj = "01191379908",
                            DataNascimento = new DateTime(1997, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@mail.com",
                            Genero = "Feminino",
                            NomeCompleto = "Maria Fernanda",
                            NumeroTelefone = "49983762147",
                            Status = 1,
                            TipoUsuario = 3
                        },
                        new
                        {
                            Id = 2,
                            Cpf_Cnpj = "01221379908",
                            DataNascimento = new DateTime(1968, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jp@mail.com",
                            Genero = "Masculino",
                            NomeCompleto = "João Paulo",
                            NumeroTelefone = "49988562147",
                            Status = 0,
                            TipoUsuario = 1
                        },
                        new
                        {
                            Id = 3,
                            Cpf_Cnpj = "01121779908",
                            DataNascimento = new DateTime(1977, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mf@mail.com",
                            Genero = "Masculino",
                            NomeCompleto = "Martin Fowler",
                            NumeroTelefone = "48988562246",
                            Status = 1,
                            TipoUsuario = 4
                        },
                        new
                        {
                            Id = 4,
                            Cpf_Cnpj = "01223378808",
                            DataNascimento = new DateTime(2004, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "martin.c.@mail.com",
                            Genero = "Masculino",
                            NomeCompleto = "Uncle Bob",
                            NumeroTelefone = "48978567216",
                            Status = 1,
                            TipoUsuario = 3
                        },
                        new
                        {
                            Id = 5,
                            Cpf_Cnpj = "01327388808",
                            DataNascimento = new DateTime(1991, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lsp@mail.com",
                            Genero = "Masculino",
                            NomeCompleto = "Barbara Liskov",
                            NumeroTelefone = "48877567116",
                            Status = 1,
                            TipoUsuario = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
